# This file was generated by FlowPilot



@dqc.expect_column_types({"Age": float, "Name": str, "Survived": str})
    """
    Reads in a pandas dataframe, defaults to titanic sample
    
    Input types:
        filepath: <class 'str'>
    
    Output type: <class 'pandas.core.frame.DataFrame'>
    """
def read(filepath: str = "./sample_data/titanic.csv") -> pd.DataFrame:
    return pd.read_csv(filepath)

