# This file was generated by FlowPilot



def test_read(df: pd.DataFrame) -> pd.DataFrame:
    """
    Test reader
    
    Input types:
        df: <class 'pandas.core.frame.DataFrame'>
    
    Output type: <class 'pandas.core.frame.DataFrame'>
    """
    return df

