# This file was generated by FlowPilot

def get_males_only(df: pd.DataFrame) -> pd.DataFrame:
    return df[df['Sex'] == "male"]


def get_survivor_age(df: pd.DataFrame) -> pd.DataFrame:
    return df.groupby(["Survived"])["Age"].mean()


