# This file was generated by FlowPilot



def get_gender_only(df: pd.DataFrame, gender: str) -> pd.DataFrame:
    """
    Filters dataset by gender
    
    Input types:
        df: <class 'pandas.core.frame.DataFrame'>
        gender: <class 'str'>
    
    Output type: <class 'pandas.core.frame.DataFrame'>
    """
    return df[df['Sex'] == gender]

def get_survivor_age(df: pd.DataFrame) -> pd.DataFrame:
    """
    Calculates avg. age by survival
    
    Input types:
        df: <class 'pandas.core.frame.DataFrame'>
    
    Output type: <class 'pandas.core.frame.DataFrame'>
    """
    return df.groupby(["Survived"])["Age"].mean()

